import { Link } from "react-router-dom";
import {
  ChevronRight, Bell, CheckCircle, ArrowRight, Phone,
  HelpCircle, FileSearch, BookOpen, Shield
} from "lucide-react";
import SEO from "../components/SEO";

const features = [
  {
    icon: HelpCircle,
    title: "Guided tax Q&A",
    desc: "Ask any income tax or GST question in plain language and receive a clear, referenced answer based on current Indian tax law.",
  },
  {
    icon: FileSearch,
    title: "Notice explanation",
    desc: "Share the text of a notice and receive a plain-language summary of what it means, what is being asked, and what the deadline is.",
  },
  {
    icon: BookOpen,
    title: "Compliance reference",
    desc: "Quick lookups for rates, due dates, section references, and threshold limits — for ITR, GST, TDS, and corporate filings.",
  },
  {
    icon: Shield,
    title: "CA-reviewed answers",
    desc: "Every response generated by the tool is reviewed against current provisions by CA. V.V.N. Prasad Gupta before it is shown to users.",
  },
];

export default function AITaxAssistant() {
  return (
    <>
      <SEO
        title="AI Tax Assistant | Guided Indian Tax Q&A"
        description="A guided research tool for Indian tax and GST queries, offering plain-language summaries and CA-reviewed answers."
        canonical="/ai-tax-assistant"
      />
      {/* ── Hero ─────────────────────────────────────── */}
      <section className="bg-white border-b border-[#E8EDE9]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 lg:py-14">
          <nav className="flex items-center gap-1.5 mb-5 text-sm text-[#4E5A54] font-body">
            <Link to="/" className="hover:text-[#1A4D2E] transition-colors">Home</Link>
            <ChevronRight size={14} className="text-[#D4DAD6]" />
            <span className="text-[#1C201E] font-medium">Tax Assistant</span>
          </nav>

          <div className="inline-flex items-center gap-2 bg-amber-50 border border-amber-200 text-amber-700 text-xs font-medium font-body rounded-full px-3.5 py-1.5 mb-5">
            <Bell size={12} strokeWidth={1.5} />
            Coming Soon — Launching Q3 2025
          </div>

          <span className="block text-[11px] uppercase tracking-[0.14em] font-semibold text-[#1A4D2E] mb-3 font-body">
            Tax Guidance Tool
          </span>
          <h1 className="font-heading font-semibold text-[1.875rem] sm:text-[2.25rem] lg:text-[2.75rem] tracking-tight leading-[1.1] text-[#1C201E] mb-4 max-w-3xl">
            Clear answers to Indian tax questions. At any hour.
          </h1>
          <p className="font-body text-base text-[#4E5A54] leading-relaxed max-w-xl mb-6">
            The TaxNext Tax Assistant is a guided research tool for Indian tax and GST queries.
            It references current rules, explains notices in plain language, and surfaces the
            right compliance information — all with CA oversight.
          </p>
          <div className="flex flex-wrap gap-x-6 gap-y-2">
            {["Built on Indian tax law", "CA. V.V.N. Prasad Gupta reviews every answer", "Free to use"].map((t) => (
              <span key={t} className="flex items-center gap-1.5 text-[0.8125rem] text-[#4E5A54] font-body">
                <CheckCircle size={13} strokeWidth={1.5} className="text-[#1A4D2E]" />
                {t}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Feature cards ─────────────────────────────── */}
      <section className="bg-[#F2F5F3] border-y border-[#E8EDE9]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 lg:py-20">
          <div className="max-w-2xl mb-10">
            <span className="block text-[11px] uppercase tracking-[0.14em] font-semibold text-[#1A4D2E] mb-3 font-body">
              What It Will Do
            </span>
            <h2 className="font-heading font-medium text-[1.875rem] sm:text-[2.25rem] text-[#1C201E] tracking-tight">
              A reference tool. Not a replacement for a CA.
            </h2>
            <p className="font-body text-[0.9375rem] text-[#4E5A54] leading-relaxed mt-3">
              The Tax Assistant is designed for standard queries and guidance — not for
              complex judgment calls that require a CA's assessment of your specific situation.
              For those, CA. V.V.N. Prasad Gupta is directly available.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 gap-5">
            {features.map((f) => {
              const Icon = f.icon;
              return (
                <div
                  key={f.title}
                  data-testid={`ai-feature-${f.title.toLowerCase().replace(/\s+/g, "-")}`}
                  className="bg-white rounded-xl border border-[#E8EDE9] p-6 shadow-sm"
                >
                  <div className="w-10 h-10 rounded-lg bg-[#e8eee9] flex items-center justify-center mb-4">
                    <Icon size={18} strokeWidth={1.5} className="text-[#1A4D2E]" />
                  </div>
                  <h3 className="font-heading font-medium text-base text-[#1C201E] mb-2">{f.title}</h3>
                  <p className="font-body text-sm text-[#4E5A54] leading-[1.7]">{f.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Notify + CA link ─────────────────────────── */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14 lg:py-16">
        <div className="grid sm:grid-cols-2 gap-5">

          {/* Notify card */}
          <div className="bg-[#1A4D2E] rounded-2xl p-8 text-white">
            <Bell size={22} strokeWidth={1.5} className="text-white/60 mb-4" />
            <h3 className="font-heading font-semibold text-xl mb-2">Get notified at launch.</h3>
            <p className="font-body text-sm text-white/70 leading-relaxed mb-6">
              Be the first to access the Tax Guidance Tool when it launches. We'll send a
              single email — no marketing list.
            </p>
            <div className="flex flex-col sm:flex-row gap-3">
              <input
                type="email"
                data-testid="ai-assistant-email-input"
                placeholder="your@email.com"
                className="flex-1 h-11 rounded-lg px-4 text-sm font-body text-[#1C201E] bg-white outline-none focus:ring-2 focus:ring-white"
              />
              <button
                data-testid="ai-assistant-notify-btn"
                className="h-11 bg-white/15 border border-white/25 text-white rounded-lg px-5 text-sm font-medium font-body hover:bg-white/20 transition-colors whitespace-nowrap"
              >
                Notify Me
              </button>
            </div>
          </div>

          {/* CTA card */}
          <div className="bg-[#F2F5F3] border border-[#E8EDE9] rounded-2xl p-8">
            <Phone size={22} strokeWidth={1.5} className="text-[#1A4D2E] mb-4" />
            <h3 className="font-heading font-medium text-xl text-[#1C201E] mb-2">
              Need an answer now?
            </h3>
            <p className="font-body text-sm text-[#4E5A54] leading-relaxed mb-6">
              The tool isn't live yet. In the meantime, CA. V.V.N. Prasad Gupta is directly available to
              answer your tax question — usually within 24 hours.
            </p>
              <Link
                to="/contact"
                data-testid="ai-contact-link"
                className="inline-flex items-center gap-2 bg-[#1A4D2E] text-white rounded-lg px-5 py-2.5 font-medium font-body text-sm hover:bg-[#133b23] transition-colors shadow-sm"
              >
                Speak to CA. V.V.N. Prasad Gupta
                <ArrowRight size={14} strokeWidth={1.5} />
              </Link>
          </div>
        </div>
      </div>
    </>
  );
}
